- name: Create config for nginx
  copy: src=devops.conf dest=/etc/nginx/conf.d/devops.conf owner=root mode=0644
  notify:
    - reload nginx
- name: Remove default config
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify:
    - reload nginx
