# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "cfengine"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"
  config.vm.provision :shell, :path => "scripts/hosts.sh"
  config.vm.provision :shell, :path => "scripts/ssh_keys.sh"
  config.vm.provision :shell, :path => "scripts/ssh_credentials.sh"
  config.vm.provision :shell, :path => "../common/scripts/timezone.sh"
  config.vm.provision :shell, :path => "../common/scripts/disable_firewall.sh"
  config.vm.provision :shell, :path => "scripts/install_cfengine.sh"

  config.vm.define :policyserver do |policyserver_config|
    policyserver_config.vm.network :hostonly, "10.11.12.13"
    policyserver_config.vm.host_name = "policyserver"
    policyserver_config.vm.provision :shell, :path => "scripts/replace-masterfiles.sh"
    policyserver_config.vm.provision :shell, :path => "scripts/add-agent.sh"
  end

  config.vm.define :client do |client_config|
    client_config.vm.network :hostonly, "10.11.12.14"
    client_config.vm.host_name = "client"
    client_config.vm.forward_port 80, 8888
    client_config.vm.provision :shell, :path => "scripts/add-agent.sh"
    client_config.vm.provision :shell, :path => "scripts/start-agent.sh"
    client_config.vm.provision :shell, :path => "scripts/ssh_test.sh"
  end
end
