#!/bin/sh

PID_FILE=/home/devops/devops.pid
APP_HOME=/home/devops
APP_JAR=devops.jar
LOGS=/home/devops/logs

case "$1" in
  start)
    if [ ! -f $PID_FILE ]; then
      echo "Starting devops..."
      sudo mkdir -p $LOGS
      cd $APP_HOME
      nohup java -jar "$APP_JAR" 1>$LOGS/stdout.log 2>$LOGS/stderr.log &
      PID=$!
      cd -
      echo "Started devops with PID: ${PID}"
      sudo touch ${PID_FILE}
      sudo echo -e "${PID}" | sudo tee ${PID_FILE}
    else
      echo "devops already running"
    fi
    ;;
  stop)
    echo "Stopping devops..."
    if [ -f $PID_FILE ]; then
      PID=`cat ${PID_FILE}`
      test -z $PID || kill $PID
      sudo rm $PID_FILE
    else
      echo "devops already stopped"
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac